name: Run Mevalim Scraper Daily

on:
  schedule:
    - cron: "0 3 * * *" # Every day at 03:00 UTC (adjust to your preferred time)
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # or your preferred Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          EMAIL2: ${{ secrets.EMAIL2 }}
          PASSWORD2: ${{ secrets.PASSWORD2 }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          python scraper.py

  keepalive:
    runs-on: ubuntu-latest
    needs: run-script
    if: ${{ github.event_name == 'schedule' }} # only run automatically, not on manual trigger
    steps:
      - name: 🌀 Checkout repo
        uses: actions/checkout@v4

      - name: 💾 Keep workflows alive (once a month)
        run: |
          if [ "$(date +%d)" = "01" ]; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git commit --allow-empty -m "chore: keep workflows alive $(date)"
            git push
          else
            echo "Not the 1st of the month — skipping keepalive commit."
          fi
